name: CI/CD to Azure AKS

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: rg-parcial
  AZURE_AKS_CLUSTER: aks-parcial
  ACR_NAME: acrparcial
  IMAGE_NAME: aks-ci-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name $ACR_NAME

      - name: Build and push Docker image to ACR
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_AKS_CLUSTER --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/$IMAGE_NAME $IMAGE_NAME=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/$IMAGE_NAME

          